### PR TITLE
Update Calorimeter_calibration.jl

### PR DESCRIPTION
**Pull request by asteinhebel**
The ECal and HCal collections of my LCIO files had slightly different names (ECal rather than Ecal, etc)

### CODE REVIEW

**Comment by jstrube** [comment]
Does the regex work for you?

**Comment by jstrube** [comment]
Can you also check in the notebook?
The best is probably to rename the existing notebook to s.th. like XXX_Example.ipynb and then remove all output from yours before checking it in.
That way, if people add functionality, it's easy to see what changed without getting bogged down by the plot differences.

**Comment by asteinhebel** [comment]
Yes, regex worked just fine. 

I uploaded my version of the notebook to my branch:
https://github.com/asteinhebel/CalorimeterCalibration/blob/master/calorimeter_calibration_example.ipynb

**Comment by jstrube** [comment]
OK, this is fine. If you have new plots you want to add, feel free to put this back here, or we can just open a new package in the [SiliconDetector](https://github.com/SiliconDetector) group.

**Pull request closed without merging**
